export const WORKSPACE_MENU_OPTIONS = [
  { key: "dashboard", label: "Dashboard", group: "Gestão" },
  { key: "relatorios", label: "Relatórios", group: "Gestão" },
  { key: "disparos", label: "Disparos", group: "Campanhas" },
  { key: "campanhas", label: "Campanhas", group: "Campanhas" },
  { key: "chat-interno", label: "Chat Interno", group: "Comunicação" },
  { key: "aquecimento", label: "Aquecimento WhatsApp", group: "Ferramentas" },
  { key: "chips", label: "Chips", group: "Sistema" },
  { key: "agente-ia", label: "Agente de IA", group: "IA" },
  { key: "construtor-fluxo", label: "Construtor de Fluxo", group: "Automação" },
  { key: "automacoes", label: "Automações", group: "Automação" },
  { key: "chat-agendamento", label: "Chat Agendamento", group: "Agenda" },
  { key: "compromissos", label: "Compromissos", group: "Agenda" },
  { key: "tutoriais", label: "Tutoriais", group: "Ajuda" },
  { key: "conversas", label: "Conversas", group: "Comunicação" },
  { key: "chamadas", label: "Chamadas", group: "Comunicação" },
  { key: "crm-kanban", label: "CRM Kanban", group: "CRM" },
  { key: "etiquetas", label: "Etiquetas", group: "CRM" },
  { key: "contatos", label: "Contatos", group: "CRM" },
  { key: "leads", label: "Leads", group: "CRM" },
  { key: "clientes", label: "Clientes", group: "CRM" },
  { key: "usuarios", label: "Usuários", group: "Sistema" },
  { key: "gestao-grupos", label: "Gestão de Grupos", group: "Sistema" },
  { key: "follow-ups", label: "Follow-ups", group: "CRM" },
  { key: "canais", label: "Canais", group: "Sistema" },
  { key: "respostas-rapidas", label: "Respostas Rápidas", group: "Comunicação" },
  { key: "biblioteca-midia", label: "Biblioteca de Mídia", group: "Ferramentas" },
  { key: "produtos", label: "Produtos", group: "Cadastros" },
  { key: "servicos", label: "Serviços", group: "Cadastros" },
  { key: "propostas", label: "Propostas", group: "CRM" },
  { key: "agenda", label: "Agenda", group: "Agenda" },
  { key: "projetos", label: "Projetos", group: "Produtividade" },
  { key: "tarefas", label: "Tarefas", group: "Produtividade" },
  { key: "departamentos", label: "Departamentos", group: "Sistema" },
  { key: "gestor-financeiro-ia", label: "Gestor Financeiro IA", group: "Financeiro" },
  { key: "faturas", label: "Faturas", group: "Financeiro" },
  { key: "financeiro", label: "Financeiro", group: "Financeiro" },
  { key: "gateways-pagamento", label: "Gateways de Pagamento", group: "Financeiro" },
  { key: "documentacao", label: "Documentação", group: "Ajuda" },
  { key: "integracoes", label: "Integrações", group: "Automação" },
  { key: "ferramentas", label: "Ferramentas", group: "Automação" },
  { key: "meta-ads", label: "Meta Ads", group: "Automação" },
  { key: "google-ads", label: "Google Ads", group: "Automação" },
  { key: "configuracoes", label: "Configurações", group: "Sistema" },
  { key: "smtp", label: "SMTP (E-mail)", group: "Sistema" },
  { key: "sip-webphone", label: "SIP / Webphone", group: "Sistema" },
  { key: "banners", label: "Banners", group: "Sistema" },
  { key: "video-tutorial", label: "Vídeo Tutorial", group: "Sistema" },
  { key: "personalizacao-menus", label: "Personalização de Menus", group: "Sistema" },
  { key: "personalizacao-lead", label: "Campos do Card do Lead", group: "Sistema" },
  { key: "reunioes", label: "Reuniões Gravadas", group: "Ferramentas" },
  { key: "pipeline-inteligente", label: "Pipeline Inteligente", group: "CRM" },
  { key: "meus-sites", label: "Meus Sites", group: "Ferramentas" },
  { key: "redes-sociais", label: "Redes Sociais", group: "Ferramentas" },
  { key: "ia-workflows", label: "Workflows de IA", group: "IA" }
];
