[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
WEBRTC_RING_GROUP=PJSIP/7001

[from-webrtc]
exten => _+X.,1,NoOp(Outbound WebRTC call to ${EXTEN})
 same => n,Set(SELECTED_DID=${FILTER(0-9,${PJSIP_HEADER(read,X-AtendZappy-DID)})})
 same => n,ExecIf($["${SELECTED_DID}" = ""]?Set(SELECTED_DID=1231970516))
 same => n,Set(CALLERID(num)=${SELECTED_DID})
 same => n,Set(PJSIP_HEADER(add,P-Preferred-Identity)=<sip:${SELECTED_DID}@voz.sobreip.com.br>)
 same => n,Dial(PJSIP/${EXTEN:1}@sobreip-endpoint,60)
 same => n,Hangup()

exten => _X.,1,NoOp(Outbound WebRTC call to ${EXTEN})
 same => n,Set(SELECTED_DID=${FILTER(0-9,${PJSIP_HEADER(read,X-AtendZappy-DID)})})
 same => n,ExecIf($["${SELECTED_DID}" = ""]?Set(SELECTED_DID=1231970516))
 same => n,Set(CALLERID(num)=${SELECTED_DID})
 same => n,Set(PJSIP_HEADER(add,P-Preferred-Identity)=<sip:${SELECTED_DID}@voz.sobreip.com.br>)
 same => n,Dial(PJSIP/${EXTEN}@sobreip-endpoint,60)
 same => n,Hangup()

[from-sobreip]
exten => 1231970516,1,NoOp(Inbound SobreIP DID ${EXTEN})
 same => n,Dial(${WEBRTC_RING_GROUP},45)
 same => n,Hangup()

exten => _X.,1,NoOp(Inbound SobreIP fallback DID ${EXTEN})
 same => n,Dial(${WEBRTC_RING_GROUP},45)
 same => n,Hangup()
