function getConfig(name, defaultValue = null) {
    // runtime configuration from window._env_ (generated by env.sh in Docker)
    if (window._env_ && window._env_[name] !== undefined) {
        return window._env_[name];
    }

    // fallback to process.env (build time)
    return process.env[name] || defaultValue;
}

export function getEnvVariable(name, defaultValue = null) {
    return getConfig(name, defaultValue);
}

export function getBackendUrl() {
    return getConfig('REACT_APP_BACKEND_URL');
}


export function getHoursCloseTicketsAuto() {
    return getConfig('REACT_APP_HOURS_CLOSE_TICKETS_AUTO');
}

export function getFrontendPort() {
    return getConfig('SERVER_PORT');
}

export function getPrimaryColor() {
    return getConfig("REACT_APP_PRIMARY_COLOR");
}

export function getPrimaryDark() {
    return getConfig("REACT_APP_PRIMARY_DARK");
}

export function getNumberSupport() {
    return getConfig("REACT_APP_NUMBER_SUPPORT");
}