export const LONG_SCRIPT = [
    "Oi, tudo bem?",
    "Tudo sim, e você?",
    "Estou bem, obrigado. O que você tem feito ultimamente?",
    "Tenho trabalhado bastante, mas também tentando tirar um tempinho pra descansar. E você?",
    "Também estou bem ocupado com alguns projetos novos, sabe como é.",
    "Que tipo de projeto?",
    "Estou criando um ebook de receitas caseiras para desinchar e emagrecer.",
    "Nossa, isso é super interessante! O que você vai incluir nele?",
    "Vou colocar receitas com ingredientes naturais, como o psyllium, que é ótimo pra ajudar na digestão.",
    "Psyllium? Nunca ouvi falar, o que é isso?",
    "É uma fibra natural que vem da casca de uma semente. Ajuda muito com a sensação de saciedade e a melhorar o trânsito intestinal.",
    "Uau, não sabia disso. Parece ser algo bem saudável.",
    "Sim, é muito bom, principalmente para quem busca uma forma mais natural de cuidar da saúde.",
    "E as outras receitas? Você já decidiu todas?",
    "Estou quase finalizando. Estou pensando em incluir algumas bebidas detox, smoothies e até umas sopas leves.",
    "Isso é incrível, adoro receitas desse tipo. Sempre estou procurando formas mais naturais de manter uma alimentação balanceada.",
    "Fico feliz em ouvir isso! Acho que você vai adorar as receitas. Estou tentando manter tudo bem simples e acessível.",
    "Isso é ótimo, porque às vezes as receitas são complicadas demais e as pessoas acabam desistindo de fazer.",
    "Exato! Minha ideia é que qualquer pessoa possa fazer, mesmo quem não tem muita experiência na cozinha.",
    "Você está planejando colocar informações nutricionais também?",
    "Sim, quero que as pessoas saibam o que estão consumindo. Vou incluir informações sobre as calorias, proteínas e fibras, por exemplo.",
    "Isso faz muita diferença. Quando você pretende lançar o ebook?",
    "Provavelmente no próximo mês. Ainda estou ajustando alguns detalhes, mas já está quase pronto.",
    "E como você vai fazer o lançamento? Vai divulgar nas redes sociais?",
    "Sim, vou usar o WhatsApp para divulgar em alguns grupos que faço parte e também nas minhas redes.",
    "Parece uma ótima estratégia. Muita gente está interessada em alimentação saudável hoje em dia.",
    "Com certeza! Acho que as pessoas estão cada vez mais preocupadas com a saúde e buscando alternativas naturais.",
    "E você sempre foi muito bom em criar esse tipo de conteúdo. Tenho certeza que vai ser um sucesso.",
    "Obrigado! Estou dando o meu melhor para entregar algo realmente valioso.",
    "E você, tem algum projeto novo em mente?",
    "Estou pensando em começar a trabalhar com algo relacionado a skincare. Estou estudando mais sobre produtos naturais para cuidar da pele.",
    "Ah, eu adoro skincare! E com produtos naturais, melhor ainda.",
    "Sim, essa é a ideia. Acho que o mercado de skincare está crescendo muito, especialmente com essa pegada mais natural.",
    "Concordo totalmente. Eu mesma prefiro produtos que não têm tantos químicos, parece que a pele responde melhor.",
    "Exatamente! Quero criar algo que as pessoas possam usar no dia a dia sem medo de irritações ou reações adversas.",
    "Você já tem algum produto específico em mente?",
    "Estou pensando em algo simples, talvez um hidratante ou uma máscara facial. Mas tudo com ingredientes que as pessoas já conhecem, como aloe vera e óleo de coco.",
    "Nossa, isso seria perfeito. Eu adoraria testar.",
    "Vou te avisar assim que tiver algo mais concreto! Estou no começo ainda, mas bem animado com as possibilidades.",
    "E vai ser um produto que você mesmo vai desenvolver ou pensa em trabalhar com alguma marca já existente?",
    "Ainda estou decidindo. A ideia inicial era fazer algo próprio, mas estou aberto a parcerias também.",
    "As parcerias podem ser uma boa, principalmente com marcas que já têm um público fiel.",
    "Sim, essa é a minha linha de pensamento também. Pode facilitar bastante na hora de divulgar o produto.",
    "E como você está se organizando com tudo isso? Deve ser bastante trabalho lidar com várias coisas ao mesmo tempo.",
    "É bastante coisa mesmo, mas estou tentando manter uma rotina bem organizada. Estou usando algumas ferramentas de produtividade para me ajudar.",
    "Quais ferramentas você está usando?",
    "Estou usando o Notion para organizar minhas ideias e projetos. Tem sido bem útil.",
    "Ah, eu já ouvi falar do Notion, mas nunca usei. Ele é fácil de usar?",
    "No começo parece um pouco complexo, mas depois que você pega o jeito, ele é super versátil. Dá para organizar praticamente tudo nele.",
    "Interessante! Vou dar uma olhada depois. Tenho precisado de algo assim para organizar minhas tarefas.",
    "Vale a pena, com certeza. Além disso, estou tentando dedicar um tempo específico para cada projeto, assim não fico tão sobrecarregado.",
    "Essa é uma boa ideia. Eu também preciso me organizar melhor, às vezes sinto que estou com muita coisa ao mesmo tempo e não consigo focar.",
    "Eu entendo, isso acontece muito. Às vezes, o mais difícil é justamente saber onde colocar nossa energia.",
    "Exatamente. E quando você tem várias ideias ao mesmo tempo, fica difícil priorizar o que fazer primeiro.",
    "Com certeza. O segredo é tentar fazer um planejamento semanal e se comprometer a seguir ele, mesmo que surjam imprevistos.",
    "Vou tentar isso. Acho que se eu planejar a semana com antecedência, consigo ser mais produtivo.",
    "Sim, e não precisa ser algo rígido. O importante é ter uma direção.",
    "Faz sentido. Vou tentar aplicar essa estratégia a partir de amanhã.",
    "Isso, comece aos poucos, e logo você vai ver a diferença.",
    "Espero que sim. E você, além do ebook e do projeto de skincare, tem mais alguma coisa em mente?",
    "Tenho algumas ideias para o futuro, mas ainda estão bem no início. Quem sabe algo mais voltado para conteúdo digital.",
    "Conteúdo digital sempre tem muita demanda, né?",
    "Sim, especialmente agora com as redes sociais em alta. Estou pensando em criar um curso ou algo nesse sentido.",
    "Sobre o quê?",
    "Talvez algo relacionado a hábitos saudáveis ou até sobre empreendedorismo digital.",
    "Empreendedorismo digital é uma área em que muita gente tem interesse. E você tem bastante experiência nisso.",
    "Pois é, acho que pode ser um bom caminho. Vou começar a esboçar algo e ver no que dá.",
    "Acho uma ótima ideia! Tenho certeza de que você vai se sair super bem.",
    "Obrigado! E você, tem pensado em algum projeto novo para o futuro?",
    "Ainda não tenho nada muito claro, mas estou sempre de olho em novas oportunidades.",
    "Isso é bom. Às vezes as ideias surgem quando a gente menos espera.",
    "Com certeza! Vou ficar atento para não perder nenhuma chance.",
    "É isso aí, nunca se sabe o que pode aparecer.",
    "Era uma vez uma linda Princesa. Mas ela tinha um encantamento sobre ela de um tipo terrível que poderia só ser quebrado pelo primeiro beijo do amor.",
    "Ela foi trancada em um castelo guardado por um terrível dragão cuspidor de fogo.",
    "Muitos bravos cavaleiros tentaram libertá-la desta terrível prisão, mas não prevaleceu. Ela esperou no fortaleza do dragão na sala mais alta de a torre mais alta para seu verdadeiro amor e o primeiro beijo do amor verdadeiro.",
    "Como se isso fosse acontecer. Que carga de...",
    "Allstar - por Smashmouth começa a tocar. Shrek continua seu dia. Enquanto em uma cidade próxima, os moradores se reúnem para ir depois do ogro.",
    "Acha que está lá?",
    "Tudo bem. Vamos obtê-lo!",
    "Uau. Aguentar. Você sabe o que essa coisa pode fazer com você?",
    "Sim, vai moer seus ossos para fazer pão.",
    "Sim, bem, na verdade, isso seria um gigante. Agora, ogros, oh, eles são muito piores.",
    "Eles vão fazer um terno de sua pele recém-descascada.",
    "Não!",
    "Eles vão raspar seu fígado. Aperte a geléia de seus olhos! Na verdade, é muito bom em torradas.",
    "De volta! De volta, fera! De volta! Eu te aviso!",
    "Esta é a parte em que você foge.",
    "E fique de fora!"
];
